### ISSUE TITLE
Fixes TODO

### ISSUE THREAD

**Issue by ateucher** [bcgov/grizzly-bear-status-indicator#16]
## Leaflet map:
- text boxes in lower left corner 
    - [x] radar chart explanation
    - [x] note about boundaries for mortality data
- [x] make text bigger in figures
- [x] put commas in big numbers

## Print version
- [x] drop decimals in table
- [x] put commas in big numbers

## HTML page
- [x] fix footer

**Comment by ateucher** [comment]
Done via #17
